version: "3.5"

services:
  nginx_first:
    image: nginx:latest
    labels:
      - "traefik.backend=nginx-first"
      - "traefik.frontend.rule=Host:foo.florasale.fun"
      - "traefik.port=80"
      - "traefik.docker.network=traefik-net"
      - "traefik.frontend.entryPoints=https"
    networks:
    - traefik-net
    - default

networks:
  traefik-net:
    external:
      name: traefik-net
