version: "3.5"

services:
  traefik:
    image: traefik
    command: >
      --api
      --docker
      --logLevel=info
      --entryPoints='Name:http Address::80 Redirect.EntryPoint:https'
      --entryPoints='Name:https Address::443 TLS'
      --acme=true
      --acme.storage=/etc/traefik/acme/acme.json
      --acme.entrypoint=https
      --acme.httpchallenge.entrypoint=http
      --acme.domains=foo.florasale.fun,bar.florasale.fun
      --acme.email=foo@bar.com
    ports:
    - "80:80"
    - "443:443"
    - "8080:8080"  # The Web UI
    networks:
    - traefik-net
    volumes:
    - traefik:/etc/traefik/acme/
    - /var/run/docker.sock:/var/run/docker.sock

volumes:
  traefik:
networks:
  traefik-net:
    name: traefik-net
